function A = A_golf(in1,in2)
%A_golf
%    A = A_golf(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    05-Dec-2023 01:30:24

I1 = in2(2,:);
I2 = in2(6,:);
c1 = in2(3,:);
c2 = in2(7,:);
l1 = in2(4,:);
l2 = in2(8,:);
m1 = in2(1,:);
m2 = in2(5,:);
mE = in2(9,:);
th2 = in1(2,:);
t2 = cos(th2);
t3 = c2.^2;
t4 = l1.^2;
t5 = l2.^2;
t6 = m2.*t3;
t7 = mE.*t5;
t8 = c2.*l1.*m2.*t2;
t9 = l1.*l2.*mE.*t2;
t10 = I2+t6+t7+t8+t9;
A = reshape([I1+t8+t9+t10+m2.*t4+mE.*t4+c1.^2.*m1,t10,t10,I2+t6+t7],[2,2]);
end
