function A = A_golf(in1,in2)
%A_golf
%    A = A_golf(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    29-Nov-2023 17:49:08

I1 = in2(2,:);
I2 = in2(6,:);
c1 = in2(3,:);
c2 = in2(7,:);
l1 = in2(4,:);
l2 = in2(8,:);
m1 = in2(1,:);
m2 = in2(5,:);
mE = in2(9,:);
th2 = in1(2,:);
t2 = cos(th2);
t3 = c2.^2;
t4 = l1.^2;
t5 = l2.^2;
t6 = m2.*t3;
t7 = mE.*t3;
t8 = mE.*t5;
t9 = c2.*l1.*m2.*t2;
t10 = c2.*l1.*mE.*t2;
t11 = I2+t6+t7+t8+t9+t10;
A = reshape([I1+t9+t10+t11+m2.*t4+mE.*t4+c1.^2.*m1,t11,t11,I2+t6+t7+t8],[2,2]);
end
