function A = A_golf(in1,in2)
%A_golf
%    A = A_golf(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    27-Nov-2023 17:14:28

I1 = in2(2,:);
I2 = in2(6,:);
c1 = in2(3,:);
c2 = in2(7,:);
l1 = in2(4,:);
m1 = in2(1,:);
m2 = in2(5,:);
th2 = in1(2,:);
t2 = cos(th2);
t3 = c2.^2;
t4 = m2.*t3;
t5 = c2.*l1.*m2.*t2;
t6 = t4+t5;
A = reshape([I1+t5+t6+c1.^2.*m1+l1.^2.*m2,t6,t6,I2+t4],[2,2]);
end
