function E = energy_golf(in1,in2)
%ENERGY_GOLF
%    E = ENERGY_GOLF(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    15-Nov-2023 17:21:21

I1 = in2(2,:);
I2 = in2(6,:);
c1 = in2(3,:);
c2 = in2(7,:);
dth1 = in1(3,:);
dth2 = in1(4,:);
g = in2(9,:);
k = in2(10,:);
l1 = in2(4,:);
m1 = in2(1,:);
m2 = in2(5,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = cos(th2);
t4 = c2.^2;
t5 = dth1.^2;
t6 = dth2.^2;
E = (I1.*t5)./2.0+(I2.*t6)./2.0+(k.*th2.^2)./2.0+(c1.^2.*m1.*t5)./2.0+(l1.^2.*m2.*t5)./2.0+g.*m2.*(l1.*t2+c2.*cos(th1+th2))+(m2.*t4.*t5)./2.0+(m2.*t4.*t6)./2.0+dth1.*dth2.*m2.*t4+c1.*g.*m1.*t2+c2.*l1.*m2.*t3.*t5+c2.*dth1.*dth2.*l1.*m2.*t3;
end
