function th1 = th1_golf(in1,in2)
%TH1_GOLF
%    TH1 = TH1_GOLF(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    05-Dec-2023 01:30:24

th1 = in1(1,:);
th1 = th1;
end
