function th1 = th1_golf(in1,in2)
%TH1_GOLF
%    TH1 = TH1_GOLF(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    27-Nov-2023 17:14:29

th1 = in1(1,:);
th1 = th1;
end
