function th1 = th1_golf(in1,in2)
%TH1_GOLF
%    TH1 = TH1_GOLF(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    29-Nov-2023 15:59:46

th1 = in1(1,:);
th1 = th1;
end
