function th2 = th2_golf(in1,in2)
%TH2_GOLF
%    TH2 = TH2_GOLF(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    15-Nov-2023 15:30:14

th2 = in1(2,:);
th2 = th2;
end
