function th2 = th2_golf(in1,in2)
%TH2_GOLF
%    TH2 = TH2_GOLF(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    30-Nov-2023 21:36:40

th2 = in1(2,:);
th2 = th2;
end
